%YAML:1.0
---
aruco_bc_nmarkers: 4
aruco_bc_mInfoType: 1
aruco_bc_markers:
  - {id: 17, corners: [ [-0.075, -0.075, 0.000], [-0.075, -0.005, 0.000], [-0.005, -0.005, 0.000], [-0.005, -0.075, 0.000] ]}
  - {id: 26, corners: [ [0.005, -0.075, 0.000], [0.005, -0.005, 0.000], [0.075, -0.005, 0.000], [0.075, -0.075, 0.000] ]}
  - {id: 32, corners: [ [-0.075, 0.005, 0.000], [-0.075, 0.075, 0.000], [-0.005, 0.075, 0.000], [-0.005, 0.005, 0.000] ]}
  - {id: 256, corners: [ [0.005, 0.005, 0.000], [0.005, 0.075, 0.000], [0.075, 0.075, 0.000], [0.075, 0.005, 0.000] ] }
