collision_primitives:
- type: BOX 
  dimensions: [0.2, 0.008, 0.12]
  pose: [0.1, 0.004, 0.06, 0.0, 0.0, 0.0]
- type: BOX 
  dimensions: [0.02, 0.02, 0.02]
  pose: [0.1, 0.012, 0.1, 0.0, 0.0, 0.0]
subframes:
- pose_xyzrpy:
  - 0.013
  - 0.0
  - 0.076
  - -pi/2
  - 0.0
  - -pi/2
  name: big_hole_1
- pose_xyzrpy:
  - 0.076
  - 0.0
  - 0.076
  - -pi/2
  - 0.0
  - -pi/2
  name: big_hole_2
- pose_xyzrpy:
  - 0.124
  - 0.0
  - 0.076
  - -pi/2
  - 0.0
  - -pi/2
  name: big_hole_3
- pose_xyzrpy:
  - 0.187
  - 0.0
  - 0.076
  - -pi/2
  - 0.0
  - -pi/2
  name: big_hole_4
- pose_xyzrpy:
  - 0.01
  - 0.0
  - 0.01
  - -pi/2
  - 0.0
  - 0.0
  name: under_outer_hole
- pose_xyzrpy:
  - 0.0
  - 0.01
  - 0.0
  - -pi/2
  - 0.0
  - -pi/2
  name: corner_1
- pose_xyzrpy:
  - 0.2
  - 0.01
  - 0.0
  - -pi/2
  - 0.0
  - -pi/2
  name: corner_2
- pose_xyzrpy:
  - 0.2
  - 0.01
  - 0.12
  - -pi/2
  - 0.0
  - -pi/2
  name: corner_3
- pose_xyzrpy:
  - 0.0
  - 0.01
  - 0.12
  - -pi/2
  - 0.0
  - -pi/2
  name: corner_4
# Position in the front
- pose_xyzrpy:
  - 0.006
  - 0.01
  - 0.030
  - -pi/2
  - 0.0
  - -pi/2
  name: screw_hole_panel1_1
- pose_xyzrpy:
  - 0.11
  - 0.01
  - 0.030
  - -pi/2
  - 0.0
  - -pi/2
  name: screw_hole_panel1_2
- pose_xyzrpy:
  - 0.131
  - 0.01
  - 0.028
  - -pi/2
  - 0.0
  - -pi/2
  name: screw_hole_panel2_1
- pose_xyzrpy:
  - 0.179
  - 0.01
  - 0.028
  - -pi/2
  - 0.0
  - -pi/2
  name: screw_hole_panel2_2
# Position in the back
- pose_xyzrpy:
  - 0.006
  - 0.0
  - 0.030
  - -pi/2
  - 0.0
  - -pi/2
  name: screw_hole_panel1_3
- pose_xyzrpy:
  - 0.11
  - 0.0
  - 0.032
  - -pi/2
  - 0.0
  - -pi/2
  name: screw_hole_panel1_4
- pose_xyzrpy:
  - 0.133
  - 0.0
  - 0.028
  - -pi/2
  - 0.0
  - -pi/2
  name: screw_hole_panel2_3
- pose_xyzrpy:
  - 0.196
  - 0.0
  - 0.028
  - -pi/2
  - 0.0
  - -pi/2
  name: screw_hole_panel2_4
- pose_xyzrpy:
  - 0.1
  - 0.03
  - 0.099
  - 0
  - pi
  - pi/2
  name: terminal_top
- pose_xyzrpy:
  - 0.092
  - 0.028
  - 0.108
  - 0
  - pi
  - 1.8325953 # pi/2 + 15deg
  name: cable_pin1
- pose_xyzrpy:
  - 0.092
  - 0.028
  - 0.092
  - 0
  - pi 
  - 1.8325953 # pi/2 + 15deg
  name: cable_pin2
- pose_xyzrpy:
  - 0.108
  - 0.028
  - 0.092
  - 0
  - pi
  - 1.308997326 # pi/2 - 15deg
  name: cable_pin3
- pose_xyzrpy:
  - 0.108
  - 0.028
  - 0.108
  - 0
  - pi
  - 1.308997326 # pi/2 - 15deg
  name: cable_pin4
grasp_points:
- grasp_name: default_grasp
  pose_xyzrpy:
  - 0.1
  - -0.015
  - 0.06
  - -pi/2
  - pi
  - pi/2
- grasp_name: terminal_grasp
  pose_xyzrpy:
  - 0.1
  - 0.008
  - 0.1
  - pi
  - pi
  - pi/2
- grasp_name: big_holes_grasp
  pose_xyzrpy:
  - 0.1
  - -0.015
  - 0.076
  - pi
  - pi
  - pi/2
  name: big_hole_4  
mesh_pose:
- pose_xyzrpy:
  - 0.2
  - 0.0
  - 0.12
  - 0.0
  - pi
  - 0.0
