# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  default_velocity_scaling_factor: 0.1
  default_acceleration_scaling_factor: 0.1
  a_bot_elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 6.28
  a_bot_finger_joint:
    min_position: -0.01
    max_position: 1.0
    has_velocity_limits: true
    max_velocity: 16
    has_acceleration_limits: true
    max_acceleration: 16
  a_bot_left_inner_finger_joint:
    has_velocity_limits: true
    max_velocity: 16
    has_acceleration_limits: true
    max_acceleration: 16
  a_bot_left_inner_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 16
    has_acceleration_limits: true
    max_acceleration: 16
  a_bot_right_inner_finger_joint:
    has_velocity_limits: true
    max_velocity: 16
    has_acceleration_limits: true
    max_acceleration: 16
  a_bot_right_inner_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 16
    has_acceleration_limits: true
    max_acceleration: 16
  a_bot_right_outer_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 16
    has_acceleration_limits: true
    max_acceleration: 16
  a_bot_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 6.28
  a_bot_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 6.28
  a_bot_wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 6.28
    has_acceleration_limits: true
    max_acceleration: 6.28
  a_bot_wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 6.28
    has_acceleration_limits: true
    max_acceleration: 6.28
  a_bot_wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 6.28
    has_acceleration_limits: true
    max_acceleration: 6.28
  b_bot_elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 6.28
  b_bot_finger_joint:
    min_position: -0.01
    max_position: 1.0
    has_velocity_limits: true
    max_velocity: 16
    has_acceleration_limits: true
    max_acceleration: 16
  b_bot_left_inner_finger_joint:
    has_velocity_limits: true
    max_velocity: 16
    has_acceleration_limits: true
    max_acceleration: 16
  b_bot_left_inner_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 16
    has_acceleration_limits: true
    max_acceleration: 16
  b_bot_right_inner_finger_joint:
    has_velocity_limits: true
    max_velocity: 16
    has_acceleration_limits: true
    max_acceleration: 16
  b_bot_right_inner_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 16
    has_acceleration_limits: true
    max_acceleration: 16
  b_bot_right_outer_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 16
    has_acceleration_limits: true
    max_acceleration: 16
  b_bot_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 6.28
  b_bot_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 3.14
    has_acceleration_limits: true
    max_acceleration: 6.28
  b_bot_wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 6.28
    has_acceleration_limits: true
    max_acceleration: 6.28
  b_bot_wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 6.28
    has_acceleration_limits: true
    max_acceleration: 6.28
  b_bot_wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 6.28
    has_acceleration_limits: true
    max_acceleration: 6.28
