collision_primitives:
- type: CYLINDER 
  dimensions: [0.075, 0.005]
  pose: [0.0375, 0.0, 0.0, 0.0, 1.5707, 0.0]
subframes:
- pose_xyzrpy:
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  name: screw_hole
- pose_xyzrpy:
  - 0.075
  - 0.0
  - 0.0
  - -pi/2
  - 0.0
  - 0.0
  name: front_tip
- pose_xyzrpy:
  - 0.026
  - 0.0
  - 0.0
  - pi/2
  - 0.0
  - pi
  name: inserted
- pose_xyzrpy:
  - 0.0
  - 0.0
  - 0.0
  - pi/2
  - 0.0
  - pi
  name: back_tip
grasp_points:
- grasp_name: grasp_1
  pose_xyzrpy:
  - 0.06
  - 0.0
  - 0.0
  - 1.5707963267948966
  - 0.0
  - 1.5707963267948966
- grasp_name: grasp_2
  pose_xyzrpy:
  - 0.06
  - 0.0
  - 0.0
  - 1.5707963267948966
  - 0.5235987755982988
  - 1.5707963267948966
- grasp_name: grasp_3
  pose_xyzrpy:
  - 0.06
  - 0.0
  - 0.0
  - 1.5707963267948966
  - 1.0471975511965976
  - 1.5707963267948966
- grasp_name: grasp_4
  pose_xyzrpy:
  - 0.06
  - 0.0
  - 0.0
  - 1.5707963267948966
  - 1.5707963267948966
  - 1.5707963267948966
- grasp_name: grasp_5
  pose_xyzrpy:
  - 0.06
  - 0.0
  - 0.0
  - 1.5707963267948966
  - 2.0943951023931953
  - 1.5707963267948966
- grasp_name: grasp_6
  pose_xyzrpy:
  - 0.06
  - 0.0
  - 0.0
  - 1.5707963267948966
  - 2.617993877991494
  - 1.5707963267948966
- grasp_name: grasp_7
  pose_xyzrpy:
  - 0.06
  - 0.0
  - 0.0
  - 1.5707963267948966
  - 3.141592653589793
  - 1.5707963267948966
- grasp_name: grasp_8
  pose_xyzrpy:
  - 0.06
  - 0.0
  - 0.0
  - 1.5707963267948966
  - 3.665191429188092
  - 1.5707963267948966
- grasp_name: grasp_9
  pose_xyzrpy:
  - 0.06
  - 0.0
  - 0.0
  - 1.5707963267948966
  - 4.1887902047863905
  - 1.5707963267948966
- grasp_name: grasp_10
  pose_xyzrpy:
  - 0.06
  - 0.0
  - 0.0
  - 1.5707963267948966
  - 4.71238898038469
  - 1.5707963267948966
- grasp_name: grasp_11
  pose_xyzrpy:
  - 0.06
  - 0.0
  - 0.0
  - 1.5707963267948966
  - 5.235987755982988
  - 1.5707963267948966
- grasp_name: grasp_12
  pose_xyzrpy:
  - 0.06
  - 0.0
  - 0.0
  - 1.5707963267948966
  - 5.759586531581287
  - 1.5707963267948966
